name: Solaris

on: [push]

jobs:
  solaris:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/solaris-vm@v1
      with:
        usesh: true
        run: |
          pwd
          ls -lah
          whoami
          env
          locale
          /usr/xpg4/bin/sh -c 'export LC_ALL=C; echo 1 abc | sort -k 1 -n -r'
